### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [jaritars/prj-rev-bwfs-dasmoto#6]
Grade: Satisfactory

Summary: Nice job on this project, the site looks good. You used some good techniques and kept your code well organized. Take a look at the issues I created for some best practice tweaks and practices. Here is a good article with some best practice examples as well: 
http://learn.shayhowe.com/html-css/writing-your-best-code/

**Comment by jaritars** [comment]
Thanks so much. Appreciate the review.
